import type { ApiOperationMethod } from '@/platform/api/operations';

import type { GovernedCapabilityId, GovernedResourceId, GovernedRoleId } from './scoped-policy';

export type OperationAuthorityActionClass = 'QUERY' | 'COMMAND';

export interface OperationAuthorityDefinition {
  readonly method: ApiOperationMethod;
  readonly path: string;
  readonly actionClass: OperationAuthorityActionClass;
  readonly roleIds: readonly GovernedRoleId[];
  readonly capabilityIds: readonly GovernedCapabilityId[];
  readonly resourceIds: readonly GovernedResourceId[];
}

/**
 * Production-final P3 operation authority metadata compiled under the selected P4 data/permission architecture.
 * This registry is descriptive authority metadata only; it does not choose multi-grant combination semantics.
 */
export const operationAuthorityDefinitions = {
  'p3s11_apin_001_get_1': {
    method: 'GET',
    path: '/public/overview',
    actionClass: 'QUERY',
    roleIds: ['ROL-001'],
    capabilityIds: ['CAP-001'],
    resourceIds: ['RES-001'],
  },
  'p3s11_apin_002_get_1': {
    method: 'GET',
    path: '/public/guidance',
    actionClass: 'QUERY',
    roleIds: ['ROL-001'],
    capabilityIds: ['CAP-001'],
    resourceIds: ['RES-001', 'RES-008'],
  },
  'p3s11_apin_003_get_1': {
    method: 'GET',
    path: '/public/guidance/{public_content_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-001'],
    capabilityIds: ['CAP-001'],
    resourceIds: ['RES-001', 'RES-008'],
  },
  'p3s11_apin_004_get_1': {
    method: 'GET',
    path: '/disclosures/effective',
    actionClass: 'QUERY',
    roleIds: [
      'ROL-001',
      'ROL-002',
      'ROL-003',
      'ROL-004',
    ],
    capabilityIds: ['CAP-001', 'CAP-003'],
    resourceIds: ['RES-002', 'RES-015'],
  },
  'p3s11_apin_005_get_1': {
    method: 'GET',
    path: '/public/next-step-options',
    actionClass: 'QUERY',
    roleIds: ['ROL-001'],
    capabilityIds: ['CAP-001', 'CAP-006'],
    resourceIds: ['RES-014'],
  },
  'p3s11_apin_039_patch_1': {
    method: 'PATCH',
    path: '/support-privacy-cases/{case_ref}',
    actionClass: 'COMMAND',
    roleIds: ['ROL-008', 'ROL-003', 'ROL-004'],
    capabilityIds: ['CAP-006', 'CAP-016'],
    resourceIds: ['RES-014', 'RES-016'],
  },
  'p3s11_apin_006_get_1': {
    method: 'GET',
    path: '/access/context',
    actionClass: 'QUERY',
    roleIds: ['ROL-002', 'ROL-003', 'ROL-004'],
    capabilityIds: ['CAP-002', 'CAP-003'],
    resourceIds: ['RES-004', 'RES-005'],
  },
  'p3s11_apin_007_get_1': {
    method: 'GET',
    path: '/access/provisioning-status',
    actionClass: 'QUERY',
    roleIds: ['ROL-002', 'ROL-005'],
    capabilityIds: ['CAP-002', 'CAP-015'],
    resourceIds: ['RES-004', 'RES-005'],
  },
  'p3s11_apin_035_post_1': {
    method: 'POST',
    path: '/access-administration/authority-changes',
    actionClass: 'COMMAND',
    roleIds: ['ROL-005', 'ROL-006'],
    capabilityIds: ['CAP-015'],
    resourceIds: ['RES-004', 'RES-005', 'RES-018'],
  },
  'p3s11_apin_008_get_1': {
    method: 'GET',
    path: '/access/notices/effective',
    actionClass: 'QUERY',
    roleIds: ['ROL-002', 'ROL-003'],
    capabilityIds: ['CAP-003'],
    resourceIds: ['RES-002', 'RES-003', 'RES-015'],
  },
  'p3s11_apin_009_post_1': {
    method: 'POST',
    path: '/access/acceptance-records',
    actionClass: 'COMMAND',
    roleIds: ['ROL-002', 'ROL-003'],
    capabilityIds: ['CAP-003'],
    resourceIds: ['RES-003'],
  },
  'p3s11_apin_010_post_1': {
    method: 'POST',
    path: '/access/recovery-requests',
    actionClass: 'COMMAND',
    roleIds: [
      'ROL-002',
      'ROL-003',
      'ROL-004',
      'ROL-005',
    ],
    capabilityIds: ['CAP-002', 'CAP-015'],
    resourceIds: ['RES-004', 'RES-005', 'RES-014'],
  },
  'p3s11_apin_011_get_1': {
    method: 'GET',
    path: '/access/recovery-requests/{recovery_ref}',
    actionClass: 'QUERY',
    roleIds: [
      'ROL-002',
      'ROL-003',
      'ROL-004',
      'ROL-005',
    ],
    capabilityIds: ['CAP-002', 'CAP-015'],
    resourceIds: ['RES-004', 'RES-005', 'RES-014'],
  },
  'p3s11_apin_012_get_1': {
    method: 'GET',
    path: '/trainee/today',
    actionClass: 'QUERY',
    roleIds: ['ROL-003'],
    capabilityIds: ['CAP-004'],
    resourceIds: [
      'RES-006',
      'RES-010',
      'RES-012',
      'RES-019',
    ],
  },
  'p3s11_apin_013_get_1': {
    method: 'GET',
    path: '/trainee/sessions/{session_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-003'],
    capabilityIds: ['CAP-004'],
    resourceIds: ['RES-009', 'RES-010', 'RES-019'],
  },
  'p3s11_apin_014_get_1': {
    method: 'GET',
    path: '/trainee/session-schedules/{session_schedule_ref}/exercise-sequence',
    actionClass: 'QUERY',
    roleIds: ['ROL-003'],
    capabilityIds: ['CAP-004'],
    resourceIds: ['RES-008', 'RES-009', 'RES-010'],
  },
  'p3s11_apin_015_get_1': {
    method: 'GET',
    path: '/trainee/session-schedules/{session_schedule_ref}/exercise-guidance',
    actionClass: 'QUERY',
    roleIds: ['ROL-003'],
    capabilityIds: ['CAP-004'],
    resourceIds: ['RES-008', 'RES-009', 'RES-010'],
  },
  'p3s11_apin_016_post_1': {
    method: 'POST',
    path: '/trainee/session-schedules/{schedule_ref}/completion-intents',
    actionClass: 'COMMAND',
    roleIds: ['ROL-003', 'ROL-012'],
    capabilityIds: ['CAP-005', 'CAP-020'],
    resourceIds: ['RES-010', 'RES-011', 'RES-012'],
  },
  'p3s11_apin_017_get_1': {
    method: 'GET',
    path: '/completion-state/{schedule_completion_or_case_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-003', 'ROL-004'],
    capabilityIds: ['CAP-005', 'CAP-013'],
    resourceIds: [
      'RES-011',
      'RES-012',
      'RES-013',
      'RES-017',
      'RES-019',
    ],
  },
  'p3s11_apin_018_get_1': {
    method: 'GET',
    path: '/account/context',
    actionClass: 'QUERY',
    roleIds: ['ROL-003', 'ROL-004'],
    capabilityIds: ['CAP-003'],
    resourceIds: [
      'RES-002',
      'RES-003',
      'RES-004',
      'RES-006',
      'RES-007',
      'RES-015',
    ],
  },
  'p3s11_apin_019_post_1': {
    method: 'POST',
    path: '/support-privacy-requests',
    actionClass: 'COMMAND',
    roleIds: ['ROL-003', 'ROL-004'],
    capabilityIds: ['CAP-006'],
    resourceIds: ['RES-014'],
  },
  'p3s11_apin_020_get_1': {
    method: 'GET',
    path: '/coach/overview',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: [
      'CAP-007',
      'CAP-008',
      'CAP-012',
      'CAP-013',
    ],
    resourceIds: [
      'RES-006',
      'RES-009',
      'RES-010',
      'RES-012',
      'RES-013',
      'RES-019',
    ],
  },
  'p3s11_apin_021_get_1': {
    method: 'GET',
    path: '/coach/trainees',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-007'],
    resourceIds: ['RES-005', 'RES-006'],
  },
  'p3s11_apin_022_get_1': {
    method: 'GET',
    path: '/coach/trainees/{trainee_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-007', 'CAP-013'],
    resourceIds: [
      'RES-006',
      'RES-010',
      'RES-012',
      'RES-013',
      'RES-019',
    ],
  },
  'p3s11_apin_023_program_collection': {
    method: 'GET',
    path: '/coach/programs',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-009'],
  },
  'p3s11_apin_023_session_collection': {
    method: 'GET',
    path: '/coach/sessions',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-009'],
  },
  'p3s11_apin_024_program_draft': {
    method: 'GET',
    path: '/coach/programs/{program_ref}/draft',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-008', 'RES-009'],
  },
  'p3s11_apin_024_session_draft': {
    method: 'GET',
    path: '/coach/sessions/{session_ref}/draft',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-008', 'RES-009'],
  },
  'p3s11_apin_025_create_program_draft': {
    method: 'POST',
    path: '/coach/program-drafts',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-008', 'RES-009'],
  },
  'p3s11_apin_025_revise_program_draft': {
    method: 'PATCH',
    path: '/coach/program-drafts/{draft_ref}',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-008', 'RES-009'],
  },
  'p3s11_apin_025_create_session_draft': {
    method: 'POST',
    path: '/coach/session-drafts',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-008', 'RES-009'],
  },
  'p3s11_apin_025_revise_session_draft': {
    method: 'PATCH',
    path: '/coach/session-drafts/{draft_ref}',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-008'],
    resourceIds: ['RES-008', 'RES-009'],
  },
  'p3s11_apin_027_create_content_draft': {
    method: 'POST',
    path: '/coach/content-drafts',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-009'],
    resourceIds: ['RES-008'],
  },
  'p3s11_apin_027_revise_content_draft': {
    method: 'PATCH',
    path: '/coach/content-drafts/{draft_ref}',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-009'],
    resourceIds: ['RES-008'],
  },
  'p3s11_apin_026_get_1': {
    method: 'GET',
    path: '/coach/exercises',
    actionClass: 'QUERY',
    roleIds: ['ROL-004', 'ROL-007'],
    capabilityIds: ['CAP-009', 'CAP-010'],
    resourceIds: ['RES-008'],
  },
  'p3s11_apin_028_post_1': {
    method: 'POST',
    path: '/content-publication-decisions',
    actionClass: 'COMMAND',
    roleIds: ['ROL-007'],
    capabilityIds: ['CAP-010'],
    resourceIds: ['RES-002', 'RES-008'],
  },
  'p3s11_apin_029_post_1': {
    method: 'POST',
    path: '/coach/schedule-release-previews',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-012'],
    resourceIds: [
      'RES-005',
      'RES-009',
      'RES-010',
      'RES-015',
    ],
  },
  'p3s11_apin_030_post_1': {
    method: 'POST',
    path: '/coach/assignment-release-commands',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004', 'ROL-012'],
    capabilityIds: ['CAP-012', 'CAP-020'],
    resourceIds: [
      'RES-005',
      'RES-009',
      'RES-010',
      'RES-015',
    ],
  },
  'p3s11_apin_036_get_1': {
    method: 'GET',
    path: '/policies',
    actionClass: 'QUERY',
    roleIds: ['ROL-007', 'ROL-004'],
    capabilityIds: ['CAP-011', 'CAP-012'],
    resourceIds: ['RES-015'],
  },
  'p3s11_apin_031_get_1': {
    method: 'GET',
    path: '/coach/completion-monitoring',
    actionClass: 'QUERY',
    roleIds: ['ROL-004'],
    capabilityIds: ['CAP-007', 'CAP-013'],
    resourceIds: [
      'RES-006',
      'RES-010',
      'RES-012',
      'RES-013',
      'RES-019',
    ],
  },
  'p3s11_apin_032_post_1': {
    method: 'POST',
    path: '/reconciliation-cases',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004', 'ROL-012'],
    capabilityIds: ['CAP-013', 'CAP-020'],
    resourceIds: [
      'RES-011',
      'RES-012',
      'RES-013',
      'RES-017',
    ],
  },
  'p3s11_apin_033_read_case': {
    method: 'GET',
    path: '/reconciliation-cases/{case_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-004', 'ROL-006'],
    capabilityIds: ['CAP-013', 'CAP-014'],
    resourceIds: ['RES-013', 'RES-017', 'RES-018'],
  },
  'p3s11_apin_033_update_proposal': {
    method: 'PATCH',
    path: '/reconciliation-cases/{case_ref}/proposal',
    actionClass: 'COMMAND',
    roleIds: ['ROL-004', 'ROL-006'],
    capabilityIds: ['CAP-013', 'CAP-014'],
    resourceIds: ['RES-013', 'RES-017', 'RES-018'],
  },
  'p3s11_apin_034_post_1': {
    method: 'POST',
    path: '/reconciliation-cases/{case_ref}/authorization-decisions',
    actionClass: 'COMMAND',
    roleIds: ['ROL-006'],
    capabilityIds: ['CAP-014'],
    resourceIds: ['RES-012', 'RES-013', 'RES-018'],
  },
  'p3s11_apin_044_get_1': {
    method: 'GET',
    path: '/audit-events',
    actionClass: 'QUERY',
    roleIds: [
      'ROL-011',
      'ROL-006',
      'ROL-007',
      'ROL-009',
      'ROL-010',
    ],
    capabilityIds: ['CAP-019'],
    resourceIds: ['RES-018'],
  },
  'p3s11_apin_037_post_1': {
    method: 'POST',
    path: '/policy-approval-decisions',
    actionClass: 'COMMAND',
    roleIds: ['ROL-007'],
    capabilityIds: ['CAP-011'],
    resourceIds: ['RES-015', 'RES-018'],
  },
  'p3s11_apin_038_collection': {
    method: 'GET',
    path: '/support-privacy-cases',
    actionClass: 'QUERY',
    roleIds: ['ROL-008'],
    capabilityIds: ['CAP-016'],
    resourceIds: ['RES-014'],
  },
  'p3s11_apin_038_detail': {
    method: 'GET',
    path: '/support-privacy-cases/{case_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-008'],
    capabilityIds: ['CAP-016'],
    resourceIds: ['RES-014'],
  },
  'p3s11_apin_040_intake': {
    method: 'POST',
    path: '/operational-incidents',
    actionClass: 'COMMAND',
    roleIds: ['ROL-009', 'ROL-008'],
    capabilityIds: ['CAP-017', 'CAP-016'],
    resourceIds: ['RES-016', 'RES-018'],
  },
  'p3s11_apin_040_collection': {
    method: 'GET',
    path: '/operational-incidents',
    actionClass: 'QUERY',
    roleIds: ['ROL-009', 'ROL-008'],
    capabilityIds: ['CAP-017', 'CAP-016'],
    resourceIds: ['RES-016', 'RES-018'],
  },
  'p3s11_apin_040_detail': {
    method: 'GET',
    path: '/operational-incidents/{incident_ref}',
    actionClass: 'QUERY',
    roleIds: ['ROL-009', 'ROL-008'],
    capabilityIds: ['CAP-017', 'CAP-016'],
    resourceIds: ['RES-016', 'RES-018'],
  },
  'p3s11_apin_048_get_1': {
    method: 'GET',
    path: '/operational-dependencies/readiness',
    actionClass: 'QUERY',
    roleIds: ['ROL-009', 'ROL-010', 'ROL-011'],
    capabilityIds: ['CAP-017', 'CAP-018', 'CAP-019'],
    resourceIds: [
      'RES-016',
      'RES-017',
      'RES-018',
      'RES-019',
    ],
  },
  'p3s11_apin_041_post_1': {
    method: 'POST',
    path: '/operational-incidents/{incident_ref}/recovery-activities',
    actionClass: 'COMMAND',
    roleIds: ['ROL-009', 'ROL-012'],
    capabilityIds: ['CAP-017', 'CAP-020'],
    resourceIds: ['RES-016', 'RES-017', 'RES-018'],
  },
  'p3s11_apin_042_read_validation_context': {
    method: 'GET',
    path: '/recovery-activities/{recovery_activity_ref}/validation',
    actionClass: 'QUERY',
    roleIds: ['ROL-010'],
    capabilityIds: ['CAP-018'],
    resourceIds: ['RES-017', 'RES-018'],
  },
  'p3s11_apin_042_submit_validation': {
    method: 'POST',
    path: '/recovery-activities/{recovery_activity_ref}/validation-submissions',
    actionClass: 'COMMAND',
    roleIds: ['ROL-010'],
    capabilityIds: ['CAP-018'],
    resourceIds: ['RES-017', 'RES-018'],
  },
  'p3s11_apin_043_post_1': {
    method: 'POST',
    path: '/recovery-validations/{validation_ref}/state-reconciliation-handoffs',
    actionClass: 'COMMAND',
    roleIds: ['ROL-010', 'ROL-012'],
    capabilityIds: ['CAP-018', 'CAP-020'],
    resourceIds: [
      'RES-012',
      'RES-013',
      'RES-017',
      'RES-019',
    ],
  },
} as const satisfies Readonly<Record<string, OperationAuthorityDefinition>>;

export type GovernedProductionOperationId = keyof typeof operationAuthorityDefinitions;

export const governedProductionOperationIds = Object.freeze(
  Object.keys(operationAuthorityDefinitions) as GovernedProductionOperationId[],
);
