export const websiteCopy = {
  en: {
    nav: ['The approach', 'Training guide', 'Your next step'],
    access: 'Member access',
    menu: 'Menu',
    home: 'Home',
    eyebrow: 'COACH MICHEL / PURPOSEFUL TRAINING',
    title: ['Progress,', 'with purpose.'],
    intro:
      'A clear plan. A considered approach. A space to focus on the work that moves you forward.',
    primary: 'Find your next step',
    secondary: 'Explore the approach',
    scroll: 'A better way to build consistency',
    orbit: ['INTENT', 'MOVEMENT', 'PROGRESSION'],
    visual:
      'A sculptural blue track representing the continuous cycle of planning, training and reviewing.',
    strip: [
      'Thoughtful planning',
      'Focused sessions',
      'Meaningful feedback',
      'One clear direction',
    ],
    methodEyebrow: 'THE COACH MICHEL APPROACH',
    methodTitle: 'Every session belongs\nto a bigger picture.',
    methodIntro:
      'Bring your training into one place, from the plan your coach prepares to the work you complete.',
    steps: [
      [
        '01',
        'Start with intention.',
        'Understand your plan and see the sessions your coach has made available to you.',
      ],
      [
        '02',
        'Focus on the work.',
        'Follow your session in order, with exercise guidance close at hand.',
      ],
      [
        '03',
        'Make progress visible.',
        'Record your completed work and return to a clear view of your training.',
      ],
    ],
    privateEyebrow: 'YOUR TRAINING SPACE',
    privateTitle: 'Less friction.\nMore focus.',
    privateBody:
      'Your assigned sessions, guidance and completion records, brought together in a private member workspace.',
    privatePoints: [
      'A clear view of your available training',
      'Guidance alongside every assigned exercise',
      'A record of what you have completed',
    ],
    journey: 'PLAN / TRAIN / REVIEW',
    finalTitle: 'Your next chapter\nstarts with a clear step.',
    finalBody: 'Explore how it works, or sign in to the workspace your coach has prepared for you.',
    footerLine: 'Training with intention. Progress with purpose.',
    privacy: 'Privacy & use',
    copyright: 'Coach Michel',
    aboutEyebrow: 'THE APPROACH',
    aboutTitle: 'A little more intention.\nA lot more direction.',
    aboutIntro:
      'Coach Michel brings the planning, guidance and reflection around your training into a single experience.',
    aboutSections: [
      [
        'A plan you can follow.',
        'Training becomes easier to navigate when the next step is clear. Your private workspace brings together the sessions assigned by your coach and the guidance you need to follow them.',
      ],
      [
        'A process you can return to.',
        'Move through a session, record the work you complete, and return to your training with its context intact.',
      ],
      [
        'A personal space.',
        'Member access is by invitation. Your available training is connected to your account and the scope of your coaching relationship.',
      ],
    ],
    guideEyebrow: 'THE TRAINING GUIDE',
    guideTitle: 'Know your way.\nFind your flow.',
    guideIntro: 'A practical introduction to using your Coach Michel workspace.',
    articles: [
      [
        '01',
        'Your first session',
        'START HERE',
        'Sign in with your invited account. Open your available sessions and select the one assigned to you. Check the session guidance before you begin.',
      ],
      [
        '02',
        'Following the sequence',
        'DURING TRAINING',
        'Use the exercise sequence to move through your assigned session. Read the guidance for each exercise and follow the plan your coach has provided.',
      ],
      [
        '03',
        'Recording your work',
        'AFTER TRAINING',
        'Submit a completion only for work you have actually completed. Wait for a confirmed result. If a request is pending, check its state before trying again.',
      ],
      [
        '04',
        'Keeping access private',
        'YOUR ACCOUNT',
        'Use your own account and keep your password private. If you need access help, use the recovery page or the existing channel with your coach.',
      ],
    ],
    disclosuresEyebrow: 'PRIVACY & USE',
    disclosuresTitle: 'Clarity is part\nof the experience.',
    disclosuresIntro: 'The essentials of using the Coach Michel website and member workspace.',
    disclosureSections: [
      [
        'Private member access',
        'The training workspace is intended for invited members. Access to training and administration depends on the permissions assigned to an account.',
      ],
      [
        'Your training information',
        'The workspace is designed to handle account details, assigned sessions and completion records. Use your own account and avoid entering information that is not needed for your training.',
      ],
      [
        'Training guidance',
        'Website and training content is general fitness information. It does not provide a medical diagnosis or replace advice from a qualified healthcare professional.',
      ],
      [
        'Current notices',
        'Applicable published notices will be presented in the member workspace. This overview is not a substitute for a complete privacy notice or terms of service.',
      ],
    ],
    nextEyebrow: 'YOUR NEXT STEP',
    nextTitle: 'The right place\nto begin.',
    nextIntro: 'Choose the path that fits where you are today.',
    choices: [
      [
        'Already a member?',
        'Sign in to reach your assigned training and account.',
        'Go to member access',
      ],
      [
        'Getting to know the approach?',
        'Explore how planning, training and reflection come together.',
        'Explore the approach',
      ],
      [
        'Need access help?',
        'Find the next step for an invitation or account recovery.',
        'Get access help',
      ],
    ],
  },
  ar: {
    nav: ['منهج التدريب', 'دليل التدريب', 'خطوتك التالية'],
    access: 'دخول الأعضاء',
    menu: 'القائمة',
    home: 'الرئيسية',
    eyebrow: 'كوتش ميشيل / تدريب هادف',
    title: ['تقدّم،', 'بهدف واضح.'],
    intro: 'خطة واضحة. نهج مدروس. ومساحة للتركيز على العمل الذي يدفعك إلى الأمام.',
    primary: 'اكتشف خطوتك التالية',
    secondary: 'تعرّف على المنهج',
    scroll: 'طريقة أوضح لبناء الاستمرارية',
    orbit: ['الهدف', 'الحركة', 'التقدّم'],
    visual: 'مسار أزرق مجسّم يرمز إلى دورة التخطيط والتدريب والمراجعة المستمرة.',
    strip: ['تخطيط مدروس', 'جلسات مركّزة', 'متابعة مفيدة', 'اتجاه واضح'],
    methodEyebrow: 'منهج كوتش ميشيل',
    methodTitle: 'كل جلسة جزء\nمن صورة أكبر.',
    methodIntro: 'اجمع تدريبك في مكان واحد، من الخطة التي يجهّزها مدربك إلى العمل الذي تنجزه.',
    steps: [
      ['01', 'ابدأ بهدف واضح.', 'تعرّف على خطتك والجلسات التي أتاحها لك مدربك.'],
      ['02', 'ركّز على التدريب.', 'اتبع جلستك بالترتيب، مع إرشادات التمارين في متناولك.'],
      ['03', 'اجعل تقدّمك واضحًا.', 'سجّل ما أنجزته وارجع إلى صورة واضحة عن تدريبك.'],
    ],
    privateEyebrow: 'مساحتك التدريبية',
    privateTitle: 'خطوات أبسط.\nتركيز أكبر.',
    privateBody: 'جلساتك المخصصة وإرشاداتك وسجل إنجازك، معًا في مساحة خاصة بالأعضاء.',
    privatePoints: ['عرض واضح لتدريبك المتاح', 'إرشادات بجانب كل تمرين مخصص', 'سجل لما أنجزته'],
    journey: 'خطّط / تدرّب / راجع',
    finalTitle: 'فصلك التالي\nيبدأ بخطوة واضحة.',
    finalBody: 'اكتشف طريقة العمل، أو سجّل الدخول إلى المساحة التي جهّزها مدربك لك.',
    footerLine: 'تدريب بنية واضحة. وتقدّم نحو هدف.',
    privacy: 'الخصوصية والاستخدام',
    copyright: 'كوتش ميشيل',
    aboutEyebrow: 'منهج التدريب',
    aboutTitle: 'وضوح في الهدف.\nوثبات في الاتجاه.',
    aboutIntro: 'يجمع كوتش ميشيل التخطيط والإرشاد ومراجعة تدريبك في تجربة واحدة.',
    aboutSections: [
      [
        'خطة تستطيع اتباعها.',
        'يصبح التدريب أوضح عندما تعرف خطوتك التالية. تجمع مساحتك الخاصة الجلسات التي يخصصها لك مدربك والإرشادات التي تحتاجها لاتباعها.',
      ],
      [
        'مسار تستطيع العودة إليه.',
        'اتبع الجلسة وسجّل العمل الذي تنجزه، ثم عُد إلى تدريبك مع الاحتفاظ بسياقه.',
      ],
      [
        'مساحة خاصة بك.',
        'دخول الأعضاء متاح بالدعوة. يرتبط تدريبك المتاح بحسابك وبنطاق علاقتك التدريبية.',
      ],
    ],
    guideEyebrow: 'دليل التدريب',
    guideTitle: 'اعرف طريقك.\nوابنِ إيقاعك.',
    guideIntro: 'مقدمة عملية لاستخدام مساحتك في كوتش ميشيل.',
    articles: [
      [
        '01',
        'جلستك الأولى',
        'ابدأ هنا',
        'سجّل الدخول بحسابك المدعو. افتح الجلسات المتاحة واختر الجلسة المخصصة لك. اقرأ الإرشادات قبل البدء.',
      ],
      [
        '02',
        'اتباع التسلسل',
        'أثناء التدريب',
        'استخدم تسلسل التمارين للانتقال في جلستك المخصصة. اقرأ إرشادات كل تمرين واتبع الخطة التي أعدها مدربك.',
      ],
      [
        '03',
        'تسجيل إنجازك',
        'بعد التدريب',
        'أرسل تأكيد الإنجاز فقط للعمل الذي أنجزته فعلًا. انتظر النتيجة المؤكدة، وإذا كان الطلب قيد المعالجة، تحقّق من حالته قبل المحاولة مجددًا.',
      ],
      [
        '04',
        'حماية حسابك',
        'حسابك',
        'استخدم حسابك الشخصي وحافظ على سرية كلمة المرور. للحصول على المساعدة، استخدم صفحة الاسترداد أو قناة التواصل الحالية مع مدربك.',
      ],
    ],
    disclosuresEyebrow: 'الخصوصية والاستخدام',
    disclosuresTitle: 'الوضوح جزء\nمن التجربة.',
    disclosuresIntro: 'أساسيات استخدام موقع كوتش ميشيل ومساحة الأعضاء.',
    disclosureSections: [
      [
        'دخول خاص بالأعضاء',
        'مساحة التدريب مخصصة للأعضاء المدعوين. يعتمد الوصول إلى التدريب والإدارة على الصلاحيات الممنوحة للحساب.',
      ],
      [
        'معلومات تدريبك',
        'صُممت المساحة للتعامل مع تفاصيل الحساب والجلسات المخصصة وسجلات الإنجاز. استخدم حسابك وتجنب إدخال معلومات لا يحتاجها تدريبك.',
      ],
      [
        'إرشادات التدريب',
        'محتوى الموقع والتدريب معلومات عامة عن اللياقة. لا يقدم تشخيصًا طبيًا ولا يحل محل نصيحة مختص صحي مؤهل.',
      ],
      [
        'الإشعارات الحالية',
        'ستُعرض الإشعارات المنشورة السارية في مساحة الأعضاء. هذه النظرة العامة لا تحل محل إشعار خصوصية كامل أو شروط استخدام.',
      ],
    ],
    nextEyebrow: 'خطوتك التالية',
    nextTitle: 'المكان المناسب\nللبداية.',
    nextIntro: 'اختر المسار المناسب لخطوتك اليوم.',
    choices: [
      ['هل أنت عضو؟', 'سجّل الدخول للوصول إلى تدريبك المخصص وحسابك.', 'دخول الأعضاء'],
      ['تريد معرفة المنهج؟', 'اكتشف كيف يجتمع التخطيط والتدريب والمراجعة.', 'تعرّف على المنهج'],
      [
        'تحتاج مساعدة في الدخول؟',
        'اكتشف الخطوة التالية للدعوة أو استرداد الحساب.',
        'مساعدة الدخول',
      ],
    ],
  },
} as const;
