create table public.reconciliation_cases (
  id uuid primary key default gen_random_uuid(),
  case_ref text not null unique check (btrim(case_ref) <> ''),
  opened_by_principal_id uuid references public.app_principals(id) on delete set null,
  status text not null,
  affected_references jsonb not null default '[]'::jsonb,
  reason text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.reconciliation_proposals (
  id uuid primary key default gen_random_uuid(),
  proposal_ref text not null unique check (btrim(proposal_ref) <> ''),
  reconciliation_case_id uuid not null references public.reconciliation_cases(id) on delete cascade,
  version_number integer not null check (version_number > 0),
  proposal jsonb not null default '{}'::jsonb,
  reason text not null check (btrim(reason) <> ''),
  evidence jsonb not null default '{}'::jsonb,
  created_by_principal_id uuid references public.app_principals(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (reconciliation_case_id, version_number)
);

create table public.reconciliation_authorization_decisions (
  id uuid primary key default gen_random_uuid(),
  decision_ref text not null unique check (btrim(decision_ref) <> ''),
  reconciliation_case_id uuid not null references public.reconciliation_cases(id) on delete restrict,
  reconciliation_proposal_id uuid references public.reconciliation_proposals(id) on delete restrict,
  decision text not null check (decision in ('APPROVE', 'DENY')),
  actor_principal_id uuid references public.app_principals(id) on delete set null,
  reason text not null check (btrim(reason) <> ''),
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.support_privacy_cases (
  id uuid primary key default gen_random_uuid(),
  case_ref text not null unique check (btrim(case_ref) <> ''),
  principal_id uuid references public.app_principals(id) on delete set null,
  request_category text not null check (btrim(request_category) <> ''),
  minimum_routing_facts jsonb not null default '{}'::jsonb,
  consent_purpose_context jsonb not null default '{}'::jsonb,
  handler_scope jsonb not null default '{}'::jsonb,
  escalation_context jsonb not null default '{}'::jsonb,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.operational_incidents (
  id uuid primary key default gen_random_uuid(),
  incident_ref text not null unique check (btrim(incident_ref) <> ''),
  classification_ref text,
  affected_references jsonb not null default '[]'::jsonb,
  detected_by_principal_id uuid references public.app_principals(id) on delete set null,
  status text not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.recovery_activities (
  id uuid primary key default gen_random_uuid(),
  recovery_activity_ref text not null unique check (btrim(recovery_activity_ref) <> ''),
  operational_incident_id uuid not null references public.operational_incidents(id) on delete cascade,
  initiated_by_principal_id uuid references public.app_principals(id) on delete set null,
  status text not null,
  activity_intent jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.recovery_validations (
  id uuid primary key default gen_random_uuid(),
  validation_ref text not null unique check (btrim(validation_ref) <> ''),
  recovery_activity_id uuid not null references public.recovery_activities(id) on delete restrict,
  validator_principal_id uuid references public.app_principals(id) on delete set null,
  result text not null,
  evidence jsonb not null default '{}'::jsonb,
  validated_at timestamptz not null default now()
);

create table public.state_reconciliation_handoffs (
  id uuid primary key default gen_random_uuid(),
  handoff_ref text not null unique check (btrim(handoff_ref) <> ''),
  recovery_validation_id uuid not null references public.recovery_validations(id) on delete restrict,
  reconciliation_case_id uuid references public.reconciliation_cases(id) on delete set null,
  target_references jsonb not null default '[]'::jsonb,
  status text not null,
  created_at timestamptz not null default now()
);

create table public.audit_events (
  id bigint generated by default as identity primary key,
  event_ref text not null unique check (btrim(event_ref) <> ''),
  actor_principal_id uuid references public.app_principals(id) on delete restrict,
  action text not null check (btrim(action) <> ''),
  category text not null check (btrim(category) <> ''),
  object_references jsonb not null default '[]'::jsonb,
  result text not null,
  reason text,
  evidence jsonb not null default '{}'::jsonb,
  before_data jsonb,
  after_data jsonb,
  correlation_ref text,
  occurred_at timestamptz not null default now()
);

create index reconciliation_cases_status_idx on public.reconciliation_cases (status, created_at);
create index reconciliation_proposals_case_idx on public.reconciliation_proposals (reconciliation_case_id, version_number);
create index support_privacy_cases_status_idx on public.support_privacy_cases (status, created_at);
create index operational_incidents_status_idx on public.operational_incidents (status, created_at);
create index recovery_activities_incident_idx on public.recovery_activities (operational_incident_id, status);
create index recovery_validations_activity_idx on public.recovery_validations (recovery_activity_id, validated_at);
create index audit_events_object_gin_idx on public.audit_events using gin (object_references);
create index audit_events_occurred_at_idx on public.audit_events (occurred_at desc);
