export const traineeCopy = {
  en: {
    today: 'Your training, in focus.',
    todayDescription: 'One clear next step. Your coach sets the plan; you make it your own.',
    sessions: 'Your sessions',
    sessionsDescription: 'The work your coach has assigned, with every exercise in its place.',
    sequence: 'Your session, step by step',
    sequenceDescription: 'Follow your coach’s instructions in the order below.',
    exercise: 'Exercise guidance',
    exerciseDescription: 'The details for your assigned exercise, together in one place.',
    completion: 'Finish with clarity',
    completionDescription: 'Record how your assigned session went.',
    confirmation: 'Your completion status',
    confirmationDescription: 'A clear record of what has been received and confirmed.',
    account: 'Make yourself at home',
    accountDescription: 'Your account, preferred language and important notices.',
    support: 'A little help, when you need it',
    supportDescription: 'Send a question about your training, account or privacy.',
    nextSession: 'YOUR NEXT SESSION',
    viewSession: 'Open session',
    allSessions: 'View all sessions',
    available: 'Ready for you',
    scheduled: 'Not released yet',
    confirmed: 'Completion confirmed',
    pending: 'Confirmation pending',
    emptyTitle: 'Your next chapter starts here.',
    emptyBody:
      'Your coach has not assigned a session yet. When a session is ready, you will find the details here.',
    noNext: 'You’re up to date.',
    noNextBody:
      'There are no released sessions waiting for you. You can revisit your sessions or ask your coach what comes next.',
    sessionsLabel: 'Assigned sessions',
    completeLabel: 'Confirmed completions',
    readyLabel: 'Ready to start',
    latest: 'Recent activity',
    noneCompleted: 'Your confirmed sessions will appear here.',
    helpTitle: 'Stay connected to your coach',
    helpBody:
      'Unsure about a session or need an adjustment? Open a support request and include the session name.',
    helpLink: 'Ask for support',
    date: 'Scheduled date (UTC)',
    exercises: 'Exercises',
    exerciseCount: 'exercises',
    viewGuidance: 'View guidance',
    summary: 'Session overview',
    noDescription: 'Your coach has not added a session summary.',
    unreleased:
      'This session is scheduled. Your coach will release its exercise details when it is ready.',
    contentUnavailable:
      'Your coach is preparing the exercise details. Please check back before starting.',
    noExercises: 'The exercise sequence is not available yet.',
    backSessions: 'Back to sessions',
    backSequence: 'Back to exercise sequence',
    finish: 'Record session completion',
    sets: 'Sets',
    reps: 'Repetitions',
    rest: 'Rest',
    seconds: 'seconds',
    notSpecified: 'Not specified',
    instructions: 'Coach’s instructions',
    noInstructions:
      'No instructions have been published for this exercise. Ask your coach before proceeding.',
    englishContent: 'This exercise is currently available in English.',
    completionNote: 'A note for your coach',
    optional: 'Optional',
    notePlaceholder: 'How did this session feel? Any questions for next time?',
    completionConsent: 'I confirm that I completed this assigned session.',
    completionHelp:
      'Submitting creates a saved record. The next page shows whether your completion has been confirmed.',
    submitCompletion: 'Submit completion',
    submitting: 'Submitting…',
    error: 'We could not save your request. Please try again. Your entry is still here.',
    conflict:
      'This session has changed or already has a completion request. Check the latest status before submitting again.',
    checkStatus: 'Check completion status',
    unavailable: 'This session is not available for completion.',
    saved: 'Your session is on the record.',
    savedBody: 'Your completion has been saved and confirmed. Your coach can see this record.',
    pendingTitle: 'Received. Awaiting confirmation.',
    pendingBody:
      'A completion request has been saved, but a confirmed completion record is not available yet.',
    noRecord: 'No completion record yet',
    noRecordBody:
      'We could not find a confirmed completion or saved request for this reference. Return to your sessions to check the current state.',
    refresh: 'Refresh status',
    completedAt: 'Completed on (UTC)',
    reference: 'Reference',
    profile: 'Your profile',
    name: 'Name',
    noName: 'Not provided',
    accountStatus: 'Account status',
    language: 'Choose your language',
    languageHelp: 'Choose the language for this website on this browser.',
    notices: 'Important notices',
    noticesBody: 'Read current notices and review your choices.',
    reviewNotices: 'Review notices',
    signOut: 'Sign out',
    category: 'What can we help with?',
    training: 'Training question',
    accountCategory: 'Account access',
    privacy: 'Privacy request',
    technical: 'Website issue',
    message: 'Your message',
    messageHelp: 'Include only the details needed to help. Maximum 2,000 characters.',
    messagePlaceholder: 'Tell us what you need help with…',
    send: 'Send request',
    sentTitle: 'Your request has been received.',
    sentBody: 'Keep the reference below. Your request is waiting for a team member to review it.',
    another: 'Send another request',
    previousRequests: 'Your recent requests',
    noRequests: 'Your support requests will appear here after you submit one.',
    supportScope:
      'A support request does not change your training plan or account permissions. A team member will review what you need.',
    status: 'Status',
    requestReceived: 'Received',
    requestInProgress: 'In progress',
    requestResolved: 'Resolved',
    requestClosed: 'Closed',
    requestOther: 'Awaiting review',
    unavailableTitle: 'This session is unavailable',
    unavailableBody: 'It may have changed or may not be assigned to your account.',
  },
  ar: {
    today: 'تدريبك، بكل وضوح.',
    todayDescription: 'خطوة تالية واضحة. مدربك يضع الخطة، وأنت تصنع التقدم.',
    sessions: 'جلساتك التدريبية',
    sessionsDescription: 'العمل الذي خصصه مدربك لك، مع تفاصيل كل تمرين.',
    sequence: 'جلستك، خطوة بخطوة',
    sequenceDescription: 'اتبع تعليمات مدربك وفق التسلسل التالي.',
    exercise: 'دليل التمرين',
    exerciseDescription: 'تفاصيل التمرين المخصص لك، في مكان واحد.',
    completion: 'اختم جلستك بوضوح',
    completionDescription: 'سجّل إتمام جلستك وشارك مدربك ملاحظاتك.',
    confirmation: 'حالة إتمام الجلسة',
    confirmationDescription: 'سجل واضح لما تم استلامه وتأكيده.',
    account: 'مساحتك الخاصة',
    accountDescription: 'حسابك واللغة المفضلة والإشعارات المهمة.',
    support: 'المساعدة حين تحتاجها',
    supportDescription: 'أرسل سؤالاً عن تدريبك أو حسابك أو خصوصيتك.',
    nextSession: 'جلستك التالية',
    viewSession: 'افتح الجلسة',
    allSessions: 'عرض جميع الجلسات',
    available: 'جاهزة لك',
    scheduled: 'لم تُتح بعد',
    confirmed: 'تم تأكيد الإتمام',
    pending: 'بانتظار التأكيد',
    emptyTitle: 'خطوتك القادمة تبدأ هنا.',
    emptyBody: 'لم يخصص مدربك جلسة لك بعد. عندما تكون الجلسة جاهزة ستجد تفاصيلها هنا.',
    noNext: 'أنت مطّلع على كل جديد.',
    noNextBody:
      'لا توجد جلسات متاحة بانتظارك. يمكنك مراجعة جلساتك أو سؤال مدربك عن الخطوة القادمة.',
    sessionsLabel: 'الجلسات المخصصة',
    completeLabel: 'جلسات مؤكدة الإتمام',
    readyLabel: 'جاهزة للبدء',
    latest: 'آخر النشاطات',
    noneCompleted: 'ستظهر جلساتك المؤكدة هنا.',
    helpTitle: 'ابقَ على تواصل مع مدربك',
    helpBody: 'لديك سؤال عن جلسة أو تحتاج إلى تعديل؟ افتح طلب دعم واذكر اسم الجلسة.',
    helpLink: 'اطلب المساعدة',
    date: 'موعد الجلسة (UTC)',
    exercises: 'التمارين',
    exerciseCount: 'تمارين',
    viewGuidance: 'عرض التعليمات',
    summary: 'نظرة على الجلسة',
    noDescription: 'لم يضف مدربك وصفاً للجلسة بعد.',
    unreleased: 'هذه الجلسة مجدولة. سيتيح مدربك تفاصيل تمارينها عندما تصبح جاهزة.',
    contentUnavailable: 'مدربك يجهز تفاصيل التمرين. يرجى التحقق مجدداً قبل البدء.',
    noExercises: 'تسلسل التمارين غير متاح بعد.',
    backSessions: 'العودة إلى الجلسات',
    backSequence: 'العودة إلى تسلسل التمارين',
    finish: 'تسجيل إتمام الجلسة',
    sets: 'المجموعات',
    reps: 'التكرارات',
    rest: 'الراحة',
    seconds: 'ثانية',
    notSpecified: 'غير محدد',
    instructions: 'تعليمات المدرب',
    noInstructions: 'لم تُنشر تعليمات لهذا التمرين بعد. استشر مدربك قبل المتابعة.',
    englishContent: 'هذا التمرين متاح حالياً باللغة الإنجليزية.',
    completionNote: 'ملاحظة لمدربك',
    optional: 'اختياري',
    notePlaceholder: 'كيف كانت هذه الجلسة؟ هل لديك أسئلة للمرة القادمة؟',
    completionConsent: 'أؤكد أنني أتممت هذه الجلسة المخصصة لي.',
    completionHelp: 'الإرسال ينشئ سجلاً محفوظاً. الصفحة التالية توضح إذا كان إتمام الجلسة قد تأكد.',
    submitCompletion: 'إرسال إتمام الجلسة',
    submitting: 'جارٍ الإرسال…',
    error: 'لم نتمكن من حفظ طلبك. حاول مرة أخرى، ما كتبته ما زال موجوداً.',
    conflict: 'تغيرت هذه الجلسة أو لديها طلب إتمام مسجل. تحقق من آخر حالة قبل الإرسال مجدداً.',
    checkStatus: 'التحقق من حالة الإتمام',
    unavailable: 'هذه الجلسة غير متاحة لتسجيل الإتمام حالياً.',
    saved: 'جلستك أصبحت في السجل.',
    savedBody: 'تم حفظ إتمام جلستك وتأكيده. يمكن لمدربك الاطلاع على هذا السجل.',
    pendingTitle: 'تم الاستلام. بانتظار التأكيد.',
    pendingBody: 'تم حفظ طلب إتمام الجلسة، لكن لا يتوفر سجل مؤكد للإتمام بعد.',
    noRecord: 'لا يوجد سجل إتمام بعد',
    noRecordBody:
      'لم نجد إتماماً مؤكداً أو طلباً محفوظاً لهذا المرجع. ارجع إلى جلساتك للتحقق من الحالة الحالية.',
    refresh: 'تحديث الحالة',
    completedAt: 'تاريخ الإتمام (UTC)',
    reference: 'المرجع',
    profile: 'ملفك الشخصي',
    name: 'الاسم',
    noName: 'غير مذكور',
    accountStatus: 'حالة الحساب',
    language: 'اختر لغتك',
    languageHelp: 'اختر لغة الموقع على هذا المتصفح.',
    notices: 'إشعارات مهمة',
    noticesBody: 'اقرأ الإشعارات الحالية وراجع اختياراتك.',
    reviewNotices: 'مراجعة الإشعارات',
    signOut: 'تسجيل الخروج',
    category: 'كيف يمكننا مساعدتك؟',
    training: 'سؤال عن التدريب',
    accountCategory: 'الوصول إلى الحساب',
    privacy: 'طلب خصوصية',
    technical: 'مشكلة في الموقع',
    message: 'رسالتك',
    messageHelp: 'أضف التفاصيل الضرورية للمساعدة فقط. الحد الأقصى ٢٠٠٠ حرف.',
    messagePlaceholder: 'أخبرنا بما تحتاج المساعدة فيه…',
    send: 'إرسال الطلب',
    sentTitle: 'تم استلام طلبك.',
    sentBody: 'احتفظ بالمرجع أدناه. طلبك بانتظار مراجعة أحد أعضاء الفريق.',
    another: 'إرسال طلب آخر',
    previousRequests: 'طلباتك الأخيرة',
    noRequests: 'ستظهر طلبات الدعم هنا بعد إرسالها.',
    supportScope:
      'طلب الدعم لا يغير خطتك التدريبية أو صلاحيات حسابك. سيراجع أحد أعضاء الفريق ما تحتاجه.',
    status: 'الحالة',
    requestReceived: 'تم الاستلام',
    requestInProgress: 'قيد المعالجة',
    requestResolved: 'تم الحل',
    requestClosed: 'مغلق',
    requestOther: 'بانتظار المراجعة',
    unavailableTitle: 'هذه الجلسة غير متاحة',
    unavailableBody: 'ربما تغيرت الجلسة أو لم تعد مخصصة لحسابك.',
  },
} as const;
